CONFIG_LINKR_BLE_BRIDGE_TEST_UART_LOOPBACK_VERIFY=y
CONFIG_LINKR_BLE_BRIDGE_TEST_UART_LOOPBACK_INTERVAL_MS=1000
CONFIG_LINKR_BLE_BRIDGE_TEST_UART_LOOPBACK_TIMEOUT_MS=200
CONFIG_LINKR_BLE_BRIDGE_TEST_UART_LOOPBACK_PAYLOAD="linkr-loopback-test"
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_FLASH=y
