CONFIG_LINKR_BLE_BRIDGE_TEST_UART_ECHO=y
CONFIG_LINKR_BLE_BRIDGE_TEST_UART_TX=y
CONFIG_LINKR_BLE_BRIDGE_TEST_UART_TX_INTERVAL_MS=1000
CONFIG_LINKR_BLE_BRIDGE_TEST_UART_TX_PAYLOAD="linkr-ble-uart-test\r\n"
